module Bullhorn
  module Rest
    module Entities
      module Lead
        extend Base

        define_methods(fields: [
          'id',
          # 'address',
          'assignedTo',
          'businessSectors',
          'campaignSource',
          # 'candidates',
          'category',
          # 'categories',
          # 'clientContacts',
          'clientCorporation',
          'comments',
          'companyName',
          'companyURL',
          # 'conversionSource',
          'customDate1',
          'customFloat1',
          'customInt1',
          'customText1',
          'customTextBlock1',
          'dateAdded',
          # 'dateLastComment',
          # 'dateLastModified',
          # # 'dateLastVisited',
          # 'description',
          # # 'distributionLists',
          # 'division',
          'email',
          # 'email2',
          # 'email3',
          # 'fax',
          # 'fax2',
          # 'fax3',
          'firstName',
          # # 'history',
          # 'isAnonymized',
          # # 'isDayLightSavingsTime',
          # 'isDeleted',
          'lastName',
          'leadSource',
          # 'massMailOptOut',
          # 'middleName',
          'mobile',
          'name', # Notes: If you create a Lead with no value in the name field, users have no way to select that Lead in the Bullhorn staffing application. If you create or modify a Lead name that is not a combination of the firstName and lastName fields, the name will be overwritten when a user saves the Lead in the Bullhorn staffing application. The name will change to a combination of the firstName and lastName fields.		
          # 'namePrefix',
          # 'nameSuffix',
          # 'nickName',
          # # 'notes',
          # 'numEmployees',
          # 'occupation',
          'owner',
          # # 'ownerCorporation',
          # 'pager',
          'phone',
          # 'phone2',
          # 'phone3',
          # 'preferredContact',
          # # 'primarySkills',
          # 'priority',
          # 'referredByPerson',
          # 'reportToPerson',
          'role',
          # 'salary',
          # 'salaryLow',
          # # 'secondarySkills',
          # 'skillSet',
          # 'smsOptIn',
          # # 'specialties',
          'status',
          # # 'tearsheets',
          # 'timeZoneOffsetEST',
          'type',
          # 'willRelocate'
        ])
      end
    end
  end
end